CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
refreshToken VARCHAR(255),
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
birth VARCHAR(100) NOT NULL,
address VARCHAR(255),
phone VARCHAR(100) NOT NULL,
gender VARCHAR(100),
super TINYINT(1) DEFAULT 0,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);